"""Just starting out

Revision ID: 1dbf1a85960
Revises: None
Create Date: 2014-01-27 22:41:18.694272

"""

# revision identifiers, used by Alembic.
revision = '1dbf1a85960'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calentry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=20), nullable=True),
    sa.Column('exchid', sa.String(length=200), nullable=True),
    sa.Column('icaluid', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calentry')
    ### end Alembic commands ###
