"""Default insert for entry

Revision ID: bcad065039e
Revises: 1dbf1a85960
Create Date: 2014-02-01 22:37:15.906449

"""

# revision identifiers, used by Alembic.
revision = 'bcad065039e'
down_revision = '1dbf1a85960'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
